### ISSUE TITLE
Wrong results for Most edited articles last month

### ISSUE THREAD

**Issue by revi** [Niharika29/database-reports#17]
[Most edited articles last month @kowiki](https://ko.wikipedia.org/wiki/위키백과:데이터베이스_보고서/지난_달에_가장_많이_편집된_문서) has [산마리노 축구 국가대표팀](https://ko.wikipedia.org/wiki/산마리노_축구_국가대표팀) but it's different from claimed 482 - it's 4 or 5 in last 30 days.

**Comment by Niharika29** [comment]
This is interesting. There are indeed 482 records in the database for edits to that page. Most of these seem Wikidata related though. It seems like User:Xaris333 is behind most (not all) of these. Here's a  the edit timestamp and comment for some of these edits-
```
MariaDB [kowiki_p]> select rc_timestamp, rc_comment from recentchanges where rc_title='산마리노_축구_국가대표팀';

| rc_timestamp   | rc_comment                                                                                                                                                                                                                                                      
| 20171126000502 | /* wbremoveclaims-remove:1| */ [[Property:P1352]]: 204, #petscan                                                                                                                                                                                                
| 20171126003009 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,212, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 19 October 2011, #quickstatements; /* wbsetqualifie... |
| 20171126003012 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,314, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 0, #quickstatements                                     |
| 20171126002853 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,202, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 24 August 2011, #quickstatements; /* wbsetqualifier... |
| 20171126003610 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,464, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 4 July 2012, #quickstatements; /* wbsetqualifier-ad... |
| 20171126003500 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,452, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 7 March 2012, #quickstatements; /* wbsetqualifier-a... |
| 20171126003526 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,456, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 11 April 2012, #quickstatements; /* wbsetqualifier-... |
| 20171126003611 | /* wbsetqualifier-add:1| */ [[Property:P1358]]: 0, #quickstatements                                                                                                                                                                                             |
| 20171126003435 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,448, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 16 February 2012, #quickstatements; /* wbsetqualifi... |
| 20171126003551 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,460, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 9 May 2012, #quickstatements; /* wbsetqualifier-add... |
| 20171126004518 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 5 September 2012, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetrefer... |
| 20171126004412 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,033, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 24 November 2016, #quickstatements; /* wbsetqualifi... |
| 20171126004350 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,765, #quickstatements; /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,571, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:... |
| 20171126004444 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 9 March 2017, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,266, #quickstatements; /* wbsetqualifier-add... |
| 20171126004449 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 8 August 2012, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,580, #quickstatements; /* wbsetqualifier-ad... |
| 20171126004427 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 12 January 2017, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,035, #quickstatements; /* wbsetqualifier-... |
| 20171126004511 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,584, #quickstatements                                                                                                                                                                                      |
| 20171126005134 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,516, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 7 April 2016, #quickstatements; /* wbsetqualifier-a... |
| 20171126005142 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 5 May 2016, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,517, #quickstatements; /* wbsetqualifier-add:1... |
| 20171126005209 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,519, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 20, #quickstatements; /* wbcreateclaim-create:1| */...  |
| 20171126005218 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 11 August 2016, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreferen... |
| 20171126005155 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,518, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 2 June 2016, #quickstatements; /* wbsetqualifier-ad... |
| 20171126005404 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,680, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126005412 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 7 November 2012, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,680, #quickstatements; /* wbsetqualifier-... |
| 20171126005452 | /* wbsetqualifier-add:1| */ [[Property:P1358]]: 28, #quickstatements; /* wbcreateclaim-create:1| */ [[Property:P1352]]: 54,965, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */...  |
| 20171126005526 | /* wbsetreference-add:2| */ [[Property:P1352]]: 56,689, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 0, #quickstatements                                                                                                                   |
| 20171126005436 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 54,964, #quickstatements; /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,683, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:... |
| 20171126005457 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,686, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 0, #quickstatements                                     |
| 20171126005522 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,689, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 February 2013, #quickstatements; /* wbsetqualifi... |
| 20171126005348 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,677, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 30 October 2012, #quickstatements; /* wbsetqualifie... |
| 20171126005726 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,701, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 0, #quickstatements                                     |
| 20171126005656 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 9 May 2013, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,698, #quickstatements; /* wbsetqualifier-add:1... |
| 20171126005555 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,692, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 March 2013, #quickstatements; /* wbsetqualifier-... |
| 20171126005624 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,695, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 11 April 2013, #quickstatements; /* wbsetqualifier-... |
| 20171126005649 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,698, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126005721 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,701, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 6 June 2013, #quickstatements                          |
| 20171126005801 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 4 July 2013, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-... |
| 20171126005751 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,704, #quickstatements                                                                                                                                                                                      |
| 20171126005822 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,707, #quickstatements                                                                                                                                                                                      |
| 20171126005854 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,710, #quickstatements                                                                                                                                                                                      |
| 20171126005832 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 8 August 2013, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreferenc... |
| 20171126005934 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 17 October 2013, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,713, #quickstatements; /* wbsetqualifier-... |
| 20171126010042 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 19 December 2013, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,719, #quickstatements; /* wbsetqualifier... |
| 20171126010006 | /* wbsetreference-add:2| */ [[Property:P1352]]: 56,716, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 0, #quickstatements                                                                                                                   |
| 20171126005903 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 12 September 2013, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetrefe... |
| 20171126010033 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,719, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126010002 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,716, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 28 November 2013, #quickstatements; /* wbsetqualifi... |
| 20171126005927 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,713, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126010153 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,725, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 13 February 2014, #quickstatements; /* wbsetqualifi... |
| 20171126010118 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,722, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 16 January 2014, #quickstatements; /* wbsetqualifie... |
| 20171126010301 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,731, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 10 April 2014, #quickstatements; /* wbsetqualifier-... |
| 20171126010228 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,728, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 13 March 2014, #quickstatements; /* wbsetqualifier-... |
| 20171126010339 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,734, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 8 May 2014, #quickstatements; /* wbsetqualifier-add... |
| 20171126010416 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,737, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 5 June 2014, #quickstatements; /* wbsetqualifier-ad... |
| 20171126010524 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,755, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 17 July 2014, #quickstatements; /* wbsetqualifier-a... |
| 20171126010614 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,759, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 18 September 2014, #quickstatements; /* wbsetqualif... |
| 20171126010548 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,757, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 0, #quickstatements                                     |
| 20171126010631 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,761, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126010541 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,757, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 August 2014, #quickstatements                       |
| 20171126010641 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 23 October 2014, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 56,761, #quickstatements; /* wbsetqualifier-... |
| 20171126011749 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,416, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 September 2017, #quickstatements; /* wbsetqualif... |
| 20171126012125 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 50,336, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 8 January 2015, #quickstatements; /* wbsetqualifier... |
| 20171126012057 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 50,333, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 18 December 2014, #quickstatements; /* wbsetqualifi... |
| 20171126012238 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 50,593, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 27 November 2014, #quickstatements; /* wbsetqualifi... |
| 20171126012337 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 54,480, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 35, #quickstatements; /* wbcreateclaim-create:1| */...  |
| 20171126012308 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 12 February 2015, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetrefer... |
| 20171126012340 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 12 March 2015, #quickstatements                                                                                                                                                                                  |
| 20171126012347 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 50,848, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 55, #quickstatements                                    |
| 20171126012737 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,418, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 23 November 2017, #quickstatements; /* wbsetqualifi... |
| 20171126013240 | /* wbsetqualifier-add:1| */ [[Property:P1358]]: 12, #quickstatements; /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,414, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */...  |
| 20171126013157 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,411, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 6 April 2017, #quickstatements; /* wbsetqualifier-a... |
| 20171126013223 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,412, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 4 May 2017, #quickstatements; /* wbsetqualifier-add... |
| 20171126013254 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 56,415, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 10 August 2017, #quickstatements; /* wbsetqualifier... |
| 20171126014210 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 3 September 2015, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 53,803, #quickstatements; /* wbsetqualifier... |
| 20171126014134 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 53,580, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 6 August 2015, #quickstatements; /* wbsetqualifier-... |
| 20171126014101 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 53,578, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 4 June 2015, #quickstatements; /* wbsetqualifier-ad... |
| 20171126014215 | /* wbsetreference-add:2| */ [[Property:P1352]]: 54,019, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P1358]]: 40, #quickstatements                                                                                                                  |
| 20171126015529 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,642, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 12 November 2008, #quickstatements                     |
| 20171126015735 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,649, #quickstatements                                                                                                          |
| 20171126015535 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,642, #quickstatements                                                                                                          |
| 20171126015727 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,649, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 17 December 2008, #quickstatements                     |
| 20171126015813 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 49,879, #quickstatements                                                                                                                                                                                      |
| 20171126015950 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,656, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 January 2009, #quickstatements; /* wbsetqualifie... |
| 20171126015830 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 19 August 1998, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreferen... |
| 20171126020022 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 43,629, #quickstatements                                                                                                          |
| 20171126020012 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 43,629, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 16 December 2005, #quickstatements                     |
| 20171126020309 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 46,407, #quickstatements                                                                                                                                                                                      |
| 20171126020209 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,663, #quickstatements                                                                                                                                                                                      |
| 20171126020303 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 April 2004, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 46,406, #quickstatements                          |
| 20171126020230 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 11 February 2009, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetrefer... |
| 20171126020246 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 46,406, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126020408 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                                                                                                    |
| 20171126020548 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,670, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetqualifier-ad... |
| 20171126020614 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 48,520, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 23 December 1997, #quickstatements; /* wbsetqualifi... |
| 20171126020633 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 18 February 1998, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetrefer... |
| 20171126020703 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 48,522, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 18 March 1998, #quickstatements; /* wbsetqualifier-... |
| 20171126020920 | /* wbsetreference-add:2| */ [[Property:P1352]]: 46,417, #quickstatements                                                                                                                                                                                        |
| 20171126020910 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 46,417, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 19 January 2005, #quickstatements                      |
| 20171126021012 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 38,187, #quickstatements                                                                                                                                                                                      |
| 20171126021031 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 13 June 1995, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements                       |
| 20171126021045 | /* wbsetreference-add:2| */ [[Property:P1352]]: 38,187, #quickstatements                                                                                                                                                                                        |
| 20171126025256 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 16 June 1999, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 41,025, #quickstatements                           |
| 20171126025235 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 41,025, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126025354 | /* wbsetreference-add:2| */ [[Property:P1352]]: 54,378, #quickstatements; /* wbcreateclaim-create:1| */ [[Property:P1352]]: 54,379, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                              |
| 20171126025417 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 March 2007, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 54,379, #quickstatements; /* wbcreateclaim-cre... |
| 20171126025314 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 41,026, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 21 July 1999, #quickstatements                         |
| 20171126025431 | /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 18 April 2007, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements                      |
| 20171126025337 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbcreateclaim-create:1| */ [[Property:P1352]]: 54,378, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-ad... |
| 20171126025623 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 May 1997, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements                                                                                                      |
| 20171126025611 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 46,617, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126025814 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,884, #quickstatements                                                                                                          |
| 20171126025630 | /* wbsetreference-add:2| */ [[Property:P1352]]: 46,617, #quickstatements                                                                                                                                                                                        |
| 20171126025802 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,884, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 8 April 2009, #quickstatements                         |
| 20171126025834 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 54,389, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126025922 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 54,390, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 24 October 2007, #quickstatements; /* wbsetqualifie... |
| 20171126025927 | /* wbsetreference-add:2| */ [[Property:P1352]]: 54,390, #quickstatements                                                                                                                                                                                        |
| 20171126025854 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 19 September 2007, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 54,389, #quickstatements                      |
| 20171126030103 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,890, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 6 May 2009, #quickstatements                           |
| 20171126030131 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,890, #quickstatements                                                                                                          |
| 20171126030403 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,896, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 3 June 2009, #quickstatements; /* wbsetqualifier-ad... |
| 20171126030854 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 31 March 2010, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,909, #quickstatements                          |
| 20171126030837 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,909, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126031110 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,915, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 28 April 2010, #quickstatements; /* wbsetqualifier-... |
| 20171126031320 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,921, #quickstatements                                                                                                          |
| 20171126031310 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,921, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P585]]: 26 May 2010, #quickstatements                          |
| 20171126031536 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 14 July 2010, #quickstatements                                                                                                                                                                                   |
| 20171126031530 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 55,927, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126031545 | /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements; /* wbsetreference-add:2| */ [[Property:P1352]]: 55,927, #quickstatements                                                                                                          |
| 20171126031658 | /* wbcreateclaim-create:1| */ [[Property:P1352]]: 46,662, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P447]]: [[Q253414]], #quickstatements                                                                                                        |
| 20171126031713 | /* wbsetqualifier-add:1| */ [[Property:P585]]: 11 April 2001, #quickstatements; /* wbsetqualifier-add:1| */ [[Property:P459]]: [[Q180825]], #quickstatements                                                                                                    |
| 20171126031725 | /* wbsetreference-add:2| */ [[Property:P1352]]: 46,662, #quickstatements                                                                                                                                                                                        |
| 20171126032041 | /* wbsetreference-add:2| */ [[Property:P1352]]: 55,938, #quickstatements 
```

**Comment by kaldari** [comment]
@Niharika29: That's normal. We should probably filter the results by rc_type or rc_source (since the report is for most edits, not most changes). You can either do rc_type<2 or rc_source = mw.edit.

**Comment by kaldari** [comment]
See https://www.mediawiki.org/wiki/Manual:Recentchanges_table for more details.

**Comment by kaldari** [comment]
Hopefully fixed in https://github.com/Niharika29/database-reports/commit/02a1e0a13331fb1a3194eb784244d134a984c454.

**Comment by Niharika29** [comment]
Oh, I see. Thanks @kaldari!

**Comment by revi** [comment]
Unfortunately it looks like itms still happening? [아이슬란드 축구 국가대표팀](https://ko.wikipedia.org/w/index.php?title=아이슬란드_축구_국가대표팀&action=history) has 9 edits in 1 month (at best, 31 days), but listed as 309.
